{
  "dependencies": {
    "python_class": "serializable_elist", 
    "python_module": "g_sorcery.g_collections", 
    "value": {
      "data": [], 
      "separator": "\n\t"
    }
  }, 
  "description": "A simple use of exception errors", 
  "eclasses": [
    "g-sorcery", 
    "gs-pypi"
  ], 
  "homepage": "", 
  "info": {
    "Author:": "rishabh saxena", 
    "Package Index Owner:": "rishabh_python"
  }, 
  "license": "", 
  "longdescription": "A simple use of exception errors", 
  "maintainer": [
    {
      "email": "piatlicki@gmail.com", 
      "name": "Jauhien Piatlicki"
    }
  ], 
  "md5": "b4dd8fea28d0d6940725e65760ce2a7a", 
  "source_uri": "https://pypi.python.org/packages/source/t/try_catch/try_catch-2.7.2.zip"
}