{
  "dependencies": {
    "python_class": "serializable_elist", 
    "python_module": "g_sorcery.g_collections", 
    "value": {
      "data": [], 
      "separator": "\n\t"
    }
  }, 
  "description": "Plone 3 Bugfixes", 
  "eclasses": [
    "g-sorcery", 
    "gs-pypi"
  ], 
  "homepage": "http://www.brainson.de/", 
  "info": {
    "Author:": "Brainson New Media GmbH, D9T GmbH", 
    "Categories": {
      "Framework": [
        "Plone"
      ], 
      "Programming Language": [
        "Python"
      ], 
      "Topic": [
        "Software Development", 
        "Libraries", 
        "Python Modules"
      ]
    }, 
    "Home Page:": "http://www.brainson.de/", 
    "License:": "GPL", 
    "Package Index Maintainer:": "seletz", 
    "Package Index Owner:": "oroch, d9t"
  }, 
  "license": "", 
  "longdescription": "Plone 3 Bugfixes", 
  "maintainer": [
    {
      "email": "piatlicki@gmail.com", 
      "name": "Jauhien Piatlicki"
    }
  ], 
  "md5": "9ec465fb2e38a114bda7a23a50d7b85b", 
  "source_uri": "https://pypi.python.org/packages/source/c/collective.plone3bugfixes/collective.plone3bugfixes-0.9.4.tar.gz"
}