{
  "dependencies": {
    "python_class": "serializable_elist", 
    "python_module": "g_sorcery.g_collections", 
    "value": {
      "data": [], 
      "separator": "\n\t"
    }
  }, 
  "description": "ODB recover lost objects from a backup", 
  "eclasses": [
    "g-sorcery", 
    "gs-pypi"
  ], 
  "homepage": "http://pypi.python.org/pypi/dm.zodb.repair", 
  "info": {
    "Author:": "Dieter Maurer", 
    "Categories": {
      "Development Status": [
        "5 - Production/Stable"
      ], 
      "Framework": [
        "Zope2"
      ], 
      "Intended Audience": [
        "Developers"
      ], 
      "License": [
        "OSI Approved", 
        "Zope Public License"
      ], 
      "Operating System": [
        "OS Independent"
      ], 
      "Programming Language": [
        "Python"
      ], 
      "Topic": [
        "Utilities"
      ]
    }, 
    "Home Page:": "http://pypi.python.org/pypi/dm.zodb.repair", 
    "Keywords:": "ZODB recovery", 
    "License:": "ZPL", 
    "Package Index Owner:": "dmaurer"
  }, 
  "license": "Zope Public License", 
  "longdescription": "ODB recover lost objects from a backup", 
  "maintainer": [
    {
      "email": "piatlicki@gmail.com", 
      "name": "Jauhien Piatlicki"
    }
  ], 
  "md5": "650fb9abd6a4b9ce6d0b668172582537", 
  "source_uri": "https://pypi.python.org/packages/source/d/dm.zodb.repair/dm.zodb.repair-1.0.tar.gz"
}